### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by KevDi** [morganstanley/modern-cpp-kafka#106]
Could this wrapper be used on Windows?
Because in the CMakeLists it links the Library against the pthread lib which is not available in Windows

**Comment by kenneth-jia** [comment]
Yes, it supports windows, and there's even CI for windows build, -- https://github.com/morganstanley/modern-cpp-kafka/blob/main/.github/workflows/kafka_api_ci_tests.yml#L270
As you could see, it might be named as `pthreadVC3` (instead of `libpthread`) in windows dev env, thus need some trick to make the `CMakelist` work.

**Comment by KevDi** [comment]
does it requires `pthread`? Because i removed that line from the `CMakeLists` and also could use the library on Windows?

**Comment by kenneth-jia** [comment]
> does it requires `pthread`? Because i removed that line from the `CMakeLists` and also could use the library on Windows?
On linux, we do need to link `pthread` lib (even though we're using the standard thread library), -- not sure whether other OS needs it? -- maybe I could have a try then.

**Comment by RPG-18** [comment]
I just carry with me https://github.com/RPG-18/plumber/tree/main/3rdparty/modern-cpp-kafka

**Comment by kenneth-jia** [comment]
@KevDi Now we don't need the `pthread` lib for windows/macOS. https://github.com/morganstanley/modern-cpp-kafka/pull/107
