### ISSUE TITLE
Building error when trying to include modern-cpp-kafka in my project

### ISSUE THREAD

**Issue by yusxu** [morganstanley/modern-cpp-kafka#110]
I am trying to use modern-cpp-kafka in my project, but I couldn't pass compile.
I am following the install step in README:
Setting C++ 17 with `set(CMAKE_CXX_STANDARD 17)` or `add_definitions(-std=c++17)` in CMakeList

`Include the include/kafka directory in your project`
by adding
`include_directories(deps/modern-cpp-kafka/modern-cpp-kafka/include/kafka)`
in CMakeList

I include this files in main.cpp
```
#include "ProducerCommon.h"
```

But, when compile, I got this
`In file included from /path/to/my/project/src/main.cpp:28:0:
/path/to/my/project/deps/modern-cpp-kafka/modern-cpp-kafka/include/kafka/ProducerCommon.h:3:27: fatal error: kafka/Project.h: No such file or directory
compilation terminated.`

I check ProducerCommon.h:3:27 and it include "kafka/Project.h"
so I add
`include_directories(deps/modern-cpp-kafka/modern-cpp-kafka/include)`
before
`include_directories(deps/modern-cpp-kafka/modern-cpp-kafka/include/kafka)`

Change include files in main.cpp
```
#include "kafka/KafkaProducer.h"
#include "kafka/ProducerCommon.h"
#include "kafka/KafkaConsumer.h"
```

then I got lots of error, such as
"not a member of" or "is not declared",
"error: ‘struct kafka::kafka::kafka::kafka::kafka::kafka::kafka::kafka::kafka::kafka::logger_impl::streambuf_entry’ has no member named ‘streambuffer’"
(yes, so many "kafka::".  logger_impl::streambuf_entry is my class, but kafka is your namespace, why did I get this error?)
and lots of "error: expected ‘}’ before end of line"
I could provide whole compile error log if you need, log may be thousands lines
I think it may be some incorrect path in my setting or wrong define in your project?

what I am missing?

modern-cpp-kafka version: release v2021.12.08
librdkafka-dev version: Installed: 0.8.6-1.1
OS version: ubuntu 16.04.2
Cmake version: 3.5.1
Gcc version: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

**Comment by yusxu** [comment]
Sorry, I am not using modern-cpp-kafka release v2021.12.08
I am using 12bae97 at main branch (latest commit)

**Comment by kenneth-jia** [comment]
Hi, @yusxu These errors are from your project. Just some suggestions,
1. The include directory should be `deps/modern-cpp-kafka/modern-cpp-kafka/include` (instead of`deps/modern-cpp-kafka/modern-cpp-kafka/include/kafka`)
2. `kafka/Project.h: No such file or directory` is quite a straight-forward error, which means you failed to set the right `include` directories for your project (the "step 1" would fix it)
3. About `struct kafka::kafka::kafka::kafka::kafka::kafka::kafka::kafka::kafka::kafka::logger_impl::streambuf_entry`, please double check the class defination.
4. It's better to upgrade your dev env (just didn't test whether the `modern-cpp-kafka` could work with these old releases). https://github.com/morganstanley/modern-cpp-kafka/blob/main/.github/workflows/kafka_api_ci_tests.yml

**Comment by kenneth-jia** [comment]
> But my dev env is not easy to upgrade because it's shared cluster running lots of other projects.

The build-in CI only tries with ubuntu 18.04/20.04 (together with installed tools, https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md) Probably ubuntu 16.04 could work (but not guaranteed)

**Comment by yusxu** [comment]
I found out that my gcc 5.4.0 doesn't support all feature of c++17.
I will check this.
Thanks!
