### ISSUE TITLE
Nested namespace not allowed in C++14

### ISSUE THREAD

**Issue by amasciotta** [morganstanley/modern-cpp-kafka#122]
I'm trying to use the library with C++14 and boost::optional. However, the usage of nested namespaces prevents me from compiling, because it's a C++17 feature. I'm using Visual Studio 2022 v17.1.0. The compiler error is [this one](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2429?view=msvc-170).

The fix is quite easy: every occurrence of

```C++
namespace first::second {
...
}
```

should be replaced with

```C++
namespace first {
  namespace second {
  ...
  }
}
```

**Comment by amasciotta** [comment]
Maybe a CI build could be added to check C++14 compatibility as declared in the docs!

**Comment by amasciotta** [comment]
Another minor C++14 compatibility issue is the usage of `[[maybe_unused]]`, that generates the following warning:
```
1><...>\modern-cpp-kafka\include\kafka\KafkaClient.h(473,11): warning C5051: attribute 'maybe_unused' requires at least '/std:c++17'; ignored
```

**Comment by kenneth-jia** [comment]
Hi, @amasciotta The `modern-cpp-kafka api` only **partially** supports `C++14`, -- it supports `g++` only while with optimization (e.g. -O2); it doesn't support `clang++`; and now we see, it doesn't support `msvc` either.
The problem is, to fully support `c++14`, the code would become quite messy, -- it's not only about the `nested namespace`, also about `inline static member variables in the class definition`, etc. Eventually, we'll forget the `c++14` and fully move to `c++17`. Since you're using `Visual Studio 2022 v17.1.0`, I guess `c++17` support should not be a problem?

**Comment by amasciotta** [comment]
> Hi, @amasciotta The `modern-cpp-kafka api` only **partially** supports `C++14`, -- it supports `g++` only while with optimization (e.g. -O2); it doesn't support `clang++`; and now we see, it doesn't support `msvc` either. The problem is, to fully support `c++14`, the code would become quite messy, -- it's not only about the `nested namespace`, also about `inline static member variables in the class definition`, etc. Eventually, we'll forget the `c++14` and fully move to `c++17`. Since you're using `Visual Studio 2022 v17.1.0`, I guess `c++17` support should not be a problem?

Unfortunately we are forced to use C++14 by other dependencies! At the moment we are using the forked version of the pull request to work around this issue, and this seems enough to compile with MSVC.

**Comment by kenneth-jia** [comment]
If it's the only fix we need (to support c++17 for msvc), seems no harm to bring it in. 🤔

**Comment by amasciotta** [comment]
> If it's the only fix we need (to support c++14 for msvc), seems no harm to bring it in. 🤔

It seems so. However, we are using the library in a very basic way, I don't know if something might pop up later on.
